use_frameworks!

target 'RxMatrixSDK_Example' do
  pod 'RxMatrixSDK', :path => '../'

  target 'RxMatrixSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
